### ISSUE TITLE
Query too slow when passing parameters

### ISSUE THREAD

**Issue by pedrodemargomes** [MonetDB/monetdb-nodejs#9]
I am trying to execute the following query:
`SELECT COUNT(*) AS "total", matricula.ano_censo AS "year" FROM matricula WHERE (matricula.tipo<=3) AND (matricula.ano_censo >= ? ) AND (matricula.ano_censo <= ? ) GROUP BY matricula.ano_censo ORDER BY matricula.ano_censo ASC`
with the paramentes `[2013, 2018]`.

When i execute the query with no parameters, changing the query string, it runs pretty quick(~2 seconds).
Eg:
```js
conn.query('SELECT COUNT(*) AS "total", matricula.ano_censo AS "year" FROM matricula WHERE (matricula.tipo<=3) AND (matricula.ano_censo >= 2013 ) AND (matricula.ano_censo <= 2018 ) GROUP BY matricula.ano_censo ORDER BY matricula.ano_censo ASC', true).then((result) => {
    resolve(result);
},(prepError) => {
    reject(new Error(prepError.message));
});
```

But when i run the same query with parameters, instead of changing the string, it gets super slow(~40 seconds).
Eg:
```js
conn.query('SELECT COUNT(*) AS "total", matricula.ano_censo AS "year" FROM matricula WHERE (matricula.tipo<=3) AND (matricula.ano_censo >= ? ) AND (matricula.ano_censo <= ? ) GROUP BY matricula.ano_censo ORDER BY matricula.ano_censo ASC', [2013, 2018], true).then((result) => {
    resolve(result);
},(prepError) => {
    reject(new Error(prepError.message));
});
```

**Comment by PedroTadim** [comment]
Hello Pedro, can you give the tuple count of "matricula" table?

**Comment by pedrodemargomes** [comment]
@PedroTadim "matricula" table has 114 tuples. For more info about the table check https://pastebin.com/cgTXqcmi.

**Comment by PedroTadim** [comment]
Ok, the tuple count is very low, it shouldn't happen. First question is what is the version of MonetDB's server the client is connected to. Second, are any other concurrent connections to the server simultaneously? If so, are they doing writes. Does this behavior happen every time?

**Comment by pedrodemargomes** [comment]
@PedroTadim 
What is the version of MonetDB's server the client is connected to? v11.31.13 
Are any other concurrent connections to the server simultaneously? No
Does this behavior happen every time? Yes

**Comment by PedroTadim** [comment]
You are using Aug-2018-SP2 release. Can you upgrade to Apr-2019-SP1 to see if you get performance benefits?

**Comment by pedrodemargomes** [comment]
@PedroTadim I upgraded and the problem continues.

**Comment by PedroTadim** [comment]
Then, I have to look on it step by step. Can you send me a dump of the table?

**Comment by pedrodemargomes** [comment]
@PedroTadim  You can download it at https://gitlab.c3sl.ufpr.br/pdg16/matricula-table-dump

**Comment by pedrodemargomes** [comment]
@PedroTadim I have executed the quey using mclient and i think the problem is in **prepare**.
When i execute the query already prepared it gets slow.
Eg:
`
sql>prepare SELECT COUNT(*) AS "total", matricula.ano_censo AS "year" FROM matricula WHERE (matricula.tipo<=3) AND (matricula.ano_censo >= ?) AND (matricula.ano_censo <= ? ) GROUP BY matricula.ano_censo ORDER BY matricula.ano_censo ASC;`
`sql>execute 7(2013,2018);` **<- ~40 seconds to respond**

**Comment by PedroTadim** [comment]
The dump is very large @pedrodemargomes, 161GB decompressed! Anyway I couldn't load the dataset because it almost fills my drive. I think you are triggering a performance problem on MonetDB because the table's primary key has 2 columns, and only of them is being used in the query. Can you make another dump where you list the columns "ano_censo" and "tipo" only? Also can you try to make it smaller, at around 3GB compressed? I would suggest you to remove the NOT NULL constraints in the columns of the table used as primary, as primary key columns are not nullable. At the same time you can re-write (matricula.ano_censo >= ?) AND (matricula.ano_censo <= ? ) to matricula.ano_censo BETWEEN ? and ?

**Comment by pedrodemargomes** [comment]
@PedroTadim  I changed to BETWEEN and the problem continues. I made a new dump only with the necessary columns. The problem still happens in this dump. You can check it at https://gitlab.c3sl.ufpr.br/pdg16/matricula-table-dump
I also tried to use different optimizers, but it didnt work.

**Comment by cekvenich** [comment]
(sorry, is this a driver issue or a SQL issue? Like if you run this from command line outside of node, is it the same?)

**Comment by PedroTadim** [comment]
This is a SQL issue, related to MonetDB internals. When I get more time, I will look back into this.

**Comment by PedroTadim** [comment]
I benchmarked the prepared statement again today on both Nov2019 and default development branches. On default, the prepared statement now rows with the same time as the non-prepared query. I don't have time to find out why, but if can you can try to install the current development branch, the issue will be gone. Otherwise you can wait for the next feature release which will come in the next few months.

**Comment by sstalin** [comment]
Closing it since it is not driver issue.

**Comment by sstalin** [comment]
closing

**Comment by sstalin** [comment]
Closing since it is not driver issue

**Comment by sstalin** [comment]
closing since it is not a driver issue
